version: '3.7'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:5.7.12'
    environment:
      MYSQL_DATABASE: petty
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -ppassword"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

###< doctrine/doctrine-bundle ###
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
#    image: petty-care:latest
    depends_on:
      - database
    ports:
      - "8000:8000"

volumes:
  db-data:
